### ISSUE TITLE
Upgrading to sbt 1.5 leads to failure to resolve dependency

### ISSUE THREAD

**Issue by SemanticBeeng** [isarn/isarn-sketches#17]
Upgrading to sbt 1.5 leads to failure to resolve `genjavadoc-plugin` transitive dependency

Not an issue with the project functionality but attempting to upgrade and feels wrong to not be able to resolve dependencies.

Upgrading to `sbt` 1.5.5 produces this
```
error] insecure HTTP request is unsupported 'Patterns(ivyPatterns=Vector(http://dl.bintray.com/content/sbt/sbt-plugin-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branc
h]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(http://dl.bintray.com/content/sbt/sbt-plugin-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)
([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false)'; switch to HTTPS or opt-in as Resolver.url("bintray-sbt-p
lugin-releases", url(...)).withAllowInsecureProtocol(true), or by using allowInsecureProtocol in repositories file                                                                                       
[error] java.lang.RuntimeException: insecure protocol is unsupported                                                                                                                                     
[error]         at scala.sys.package$.error(package.scala:30)                                       
[error]         at sbt.Classpaths$.errorInsecureProtocol(Defaults.scala:3312)                       
[error]         at sbt.Classpaths$.$anonfun$mkIvyConfiguration$1(Defaults.scala:3906)               
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)                           
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)       
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)                               
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)                                 
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)             
[error]         at sbt.Execute.work(Execute.scala:291)                                              
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)                                 
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)                   
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)               
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)               
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
```

Fixing the resolver urls to use https produces this
```
sbt:isarn-sketches> compile
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn]  Note: Unresolved dependencies path:
[error] stack trace is suppressed; run last isarn_sketches_java / update for the full output
[error] (isarn_sketches_java / update) sbt.librarymanagement.ResolveException: Error downloading com.typesafe.genjavadoc:genjavadoc-plugin_2.12.14:0.15
[error]   Not found
[error]   Not found
[error]   not found: /development/projects/10_misc/isarn-sketches/isarn-sketches/project/.ivy/localcom.typesafe.genjavadoc/genjavadoc-plugin_2.12.14/0.15/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_2.12.14/0.15/genjavadoc-plugin_2.12.14-0.15.pom
```

Have tried a number of things locating this plugin but am stuck.

**Comment by erikerlandson** [comment]
This might help - I ran into this problem on another project and a community member fixed it here:
https://github.com/erikerlandson/coulomb/pull/201

**Comment by SemanticBeeng** [comment]
Since the error seems to be caused by a combination of sbt 1.5 and scala 1.12 have tried to reproduce with that branch but unfortunately it does not build for scala 1.12 

Also, this project uses `GenJavadocPlugin` (cause of the dependency error) but `coulomb` does not. :thinking: 

PS: Created https://github.com/isarn/isarn-sketches/pull/18 for visibility
@erikerlandson .
